import express from 'express';
import attendanceRouter from './attendance.route.js';
import attendanceOtherRouter from './attendanceOthers.route.js';
import classRouter from './class.route.js';
import classOtherRouter from './classOthers.route.js';
import examRouter from './exam.route.js';
import examOthersRouter from './examOthers.route.js';
import examResultRouter from './examResult.route.js';
import examResultOtherRouter from './examResultOther.route.js';
import feeRouter from './fee.route.js';
import feeOtherRouter from './feeOthers.route.js';
import schoolsRouter from './schools.route.js';
import staffSalaryRouter from './staffSalary.route.js';
import staffSalaryOthersRouter from './staffSalaryOthers.route.js';
import studentRouter from './student.route.js';
import studentOthersRouter from './studentOthers.route.js';
import subjectRouter from './subject.route.js';
import subjectOthersRouter from './subjectOthers.route.js';
import teacherRouter from './teacher.route.js';
import teacherOthersRouter from './teacherOthers.route.js';
import timetableRouter from './timetable.route.js';
import userRouter from './users.route.js';
import sectionRouter from './section.route.js';
import sectionOthersRouter from './sectionOthers.route.js';
import expenseRouter from './expense.route.js';
import parentRouter from './parent.route.js';
import applicationRouter from './application.route.js';
import courseRouter from './course.route.js';
import courseOthersRouter from './courseOthers.route.js';
import { authenticate } from '../config/authenticate.js';
import studentFeeRouter from './studentFee.route.js';
import userOthersRouter from './userOthers.route.js';
import departmentRouter from './department.route.js';
import libraryRouter from './library.route.js';
import asssignmentRouter from './assignment.route.js';
import dashboardRouter from './dashboard.route.js';

const router = express.Router();

router.get('/', (req, res) => {
  res.send('Welcome to the SMS API');
});

router.use('/schools', schoolsRouter);
router.use('/attendances', authenticate, attendanceRouter);
router.use('/attendancesOthers', authenticate, attendanceOtherRouter);
router.use('/classes', authenticate, classRouter);
router.use('/classesOthers', authenticate, classOtherRouter);
router.use('/exams',authenticate, examRouter);
router.use('/examsOthers', authenticate, examOthersRouter);
router.use('/examResults', authenticate, examResultRouter);
router.use('/examResultsOthers',authenticate, examResultOtherRouter);
router.use('/fees', authenticate, feeRouter);
router.use('/feeOthers', authenticate, feeOtherRouter);
router.use('/studentFees', authenticate, studentFeeRouter);
router.use('/staffSalary',authenticate, staffSalaryRouter);
router.use('/staffSalaryOthers', authenticate, staffSalaryOthersRouter);
router.use('/students', authenticate, studentRouter);
router.use('/studentOthers', authenticate, studentOthersRouter);
router.use('/subjects', authenticate, subjectRouter);
router.use('/subjectOthers', authenticate, subjectOthersRouter);
router.use('/teachers', authenticate, teacherRouter);
router.use('/teacherOthers', authenticate, teacherOthersRouter);
router.use('/timetable',authenticate, timetableRouter);
router.use('/users', userRouter);
router.use('/section', authenticate, sectionRouter);
router.use('/sectionOthers',authenticate, sectionOthersRouter);
router.use('/expense', authenticate, expenseRouter);
router.use('/parents', authenticate, parentRouter);
router.use('/applications', authenticate, applicationRouter);
router.use('/courses', authenticate, courseRouter);
router.use('/courseOthers', authenticate, courseOthersRouter);
router.use('/userOthers', authenticate, userOthersRouter);
router.use("/departments", authenticate, departmentRouter);
router.use("/library",authenticate, libraryRouter);
router.use("/assignments", authenticate, asssignmentRouter);
router.use("/dashboard", authenticate, dashboardRouter);

export default router;